services:
  web:
    image: php:8.2-fpm
    volumes:
      - ./docker/php/src:/var/www/html
    ports:
      - 9000:9000
    depends_on:
      - db

  db:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DB-PRJ
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    ports:
      - 8080:8080

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/conf:/etc/nginx/conf.d
      - ./docker/nginx/html:/var/www/html
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  db_data:
