CREATE DATABASE IF NOT EXISTS DB-PRJ;
USE DB-PRJ;
CREATE TABLE IF NOT EXISTS users (
id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(50) NOT NULL
);

INSERT INTO users (name) VALUES ('Sai'), ('Adrien'), ('Gaetan');
