name: CI/CD - LAMP Project

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test:
    name: Build and Test Containers
    runs-on: ubuntu-latest
  steps:
    - name: Récupération du code source
      uses: actions/checkout@v4
