name: CI/CD - LAMP Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  php-test:
    name: Test Containers
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code source
        uses: actions/checkout@v3
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
         php-version: '8.2'
      - name: PHP Syntax Check
        run: find web/ -name "*.php" -exec php -l {}\;
